export type SourceAuthority = "national-programme" | "regulatory" | "formulary" | "pharmacovigilance" | "guideline" | "evidence-review" | "drug-reference" | "clinical-tool" | "research";
export type AccessType = "open" | "restricted" | "registration-required";
export type IngestionMode = "pdf" | "html" | "api" | "metadata-only";

export interface ResourceMeta {
  id: string;
  displayName: string;
  category: string;
  subcategory: string;
  description: string;
  officialUrl: string;
  countryOrRegion: string;
  indiaPriority: number;   // 1 = highest India priority, 0 = not India-specific
  globalPriority: number;  // 1–5 (1 = top global authority)
  sourceAuthorityLevel: SourceAuthority;
  accessType: AccessType;
  licenseStatus: string;
  allowedUseNotes: string;
  attributionRequired: boolean;
  redistributionAllowed: boolean;
  localStorageAllowed: boolean;
  ingestionMode: IngestionMode;
  updateFrequency: string;
  supportsApi: boolean;
  supportsBulkDownload: boolean;
  requiresRegistration: boolean;
  priorityScore: number;   // composite 0–100, higher = prefer in ranking
  tags: string[];
  clinicalUseCases: string[];
  dataTypes: string[];
  sourceReliabilityLevel: "high" | "moderate" | "low";
  lastLicenseReviewAt: string;
}

export const RESOURCE_REGISTRY: ResourceMeta[] = [
  // ── India national programme (priority tier 1) ────────────────────────────
  {
    id: "ntep-tb",
    displayName: "NTEP / Central TB Division",
    category: "India Guidelines",
    subcategory: "National Programme",
    description: "India National TB Elimination Programme — TB regimens, MDR/RR-TB, preventive therapy",
    officialUrl: "https://tbcindia.mohfw.gov.in/guidelines/",
    countryOrRegion: "India",
    indiaPriority: 1,
    globalPriority: 1,
    sourceAuthorityLevel: "national-programme",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official MoHFW programme document. Full text ingestion permitted for clinical reference.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "pdf",
    updateFrequency: "annual",
    supportsApi: false,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 98,
    tags: ["India", "MoHFW", "NTEP", "tuberculosis", "TB", "MDR-TB", "national-programme", "india-guideline"],
    clinicalUseCases: ["TB treatment", "MDR/RR-TB", "latent TB", "TB preventive therapy", "programme guidance"],
    dataTypes: ["treatment-guideline", "drug-regimen", "programme-protocol"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  {
    id: "naco-hiv",
    displayName: "NACO HIV Guidelines",
    category: "India Guidelines",
    subcategory: "National Programme",
    description: "India NACO — National AIDS Control Organisation HIV care, ART, PEP, PMTCT guidelines",
    officialUrl: "https://naco.mohfw.gov.in/guidelines",
    countryOrRegion: "India",
    indiaPriority: 1,
    globalPriority: 1,
    sourceAuthorityLevel: "national-programme",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official MoHFW/NACO programme document. Full text ingestion permitted.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "pdf",
    updateFrequency: "biennial",
    supportsApi: false,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 98,
    tags: ["India", "MoHFW", "NACO", "HIV", "ART", "PEP", "PMTCT", "national-programme", "india-guideline"],
    clinicalUseCases: ["HIV treatment", "ART initiation", "PEP", "PMTCT", "opportunistic infections"],
    dataTypes: ["treatment-guideline", "drug-regimen", "programme-protocol"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  {
    id: "ncvbdc-malaria",
    displayName: "NCVBDC / NVBDCP Malaria Guidelines",
    category: "India Guidelines",
    subcategory: "National Programme",
    description: "India NCVBDC — malaria treatment, resistance policy, diagnosis national programme guidance",
    officialUrl: "https://ncvbdc.mohfw.gov.in",
    countryOrRegion: "India",
    indiaPriority: 1,
    globalPriority: 1,
    sourceAuthorityLevel: "national-programme",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official MoHFW programme document. Full text ingestion permitted.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "pdf",
    updateFrequency: "irregular",
    supportsApi: false,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 97,
    tags: ["India", "MoHFW", "NCVBDC", "NVBDCP", "malaria", "vector-borne-disease", "national-programme", "india-guideline"],
    clinicalUseCases: ["malaria treatment", "Plasmodium vivax", "Plasmodium falciparum", "drug resistance"],
    dataTypes: ["treatment-guideline", "drug-regimen", "programme-protocol"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  {
    id: "uip-immunization",
    displayName: "UIP / National Immunization Schedule",
    category: "India Guidelines",
    subcategory: "National Programme",
    description: "India UIP — Universal Immunization Programme national vaccine schedule (NHM/MoHFW)",
    officialUrl: "https://nhm.gov.in",
    countryOrRegion: "India",
    indiaPriority: 1,
    globalPriority: 1,
    sourceAuthorityLevel: "national-programme",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official NHM/MoHFW programme document. Full text ingestion permitted.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "pdf",
    updateFrequency: "annual",
    supportsApi: false,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 97,
    tags: ["India", "MoHFW", "NHM", "UIP", "immunization", "vaccine", "national-programme", "india-guideline"],
    clinicalUseCases: ["immunization schedule", "vaccine recommendations", "childhood vaccines", "adult vaccines"],
    dataTypes: ["vaccine-schedule", "programme-protocol"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  // ── India drug/formulary/regulatory (priority tier 2) ─────────────────────
  {
    id: "nlem-2022",
    displayName: "NLEM 2022",
    category: "India Drug Safety",
    subcategory: "Formulary",
    description: "India NLEM 2022 (National List of Essential Medicines) — CDSCO/MoHFW rational prescribing reference",
    officialUrl: "https://cdsco.gov.in",
    countryOrRegion: "India",
    indiaPriority: 2,
    globalPriority: 2,
    sourceAuthorityLevel: "formulary",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official CDSCO/MoHFW document. Full text ingestion permitted.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "pdf",
    updateFrequency: "irregular",
    supportsApi: false,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 95,
    tags: ["India", "CDSCO", "NLEM", "essential-medicines", "formulary", "rational-use", "india-drug-safety"],
    clinicalUseCases: ["essential medicines identification", "rational prescribing", "formulary reference"],
    dataTypes: ["drug-list", "formulary"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  {
    id: "nfi",
    displayName: "National Formulary of India (NFI)",
    category: "India Drug Safety",
    subcategory: "Formulary",
    description: "India NFI 2021 — IPC authoritative formulary for prescribing, dispensing, administration",
    officialUrl: "https://www.ipc.gov.in/mandates/nfi/about-nfi.html",
    countryOrRegion: "India",
    indiaPriority: 2,
    globalPriority: 2,
    sourceAuthorityLevel: "formulary",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official IPC document. Full text ingestion permitted.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "pdf",
    updateFrequency: "irregular",
    supportsApi: false,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 94,
    tags: ["India", "IPC", "NFI", "formulary", "prescribing", "rational-use", "india-drug-safety"],
    clinicalUseCases: ["drug prescribing reference", "dispensing guidance", "dose reference"],
    dataTypes: ["drug-monograph", "formulary"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  {
    id: "cdsco-alerts",
    displayName: "CDSCO Drug Alerts / NSQ / Banned Drugs",
    category: "India Drug Safety",
    subcategory: "Regulatory",
    description: "India CDSCO — drug regulatory status, NSQ alerts, banned/restricted medicines, spurious drug notices",
    officialUrl: "https://cdsco.gov.in",
    countryOrRegion: "India",
    indiaPriority: 2,
    globalPriority: 2,
    sourceAuthorityLevel: "regulatory",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official CDSCO regulatory notices. Full text ingestion permitted.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "html",
    updateFrequency: "weekly",
    supportsApi: false,
    supportsBulkDownload: false,
    requiresRegistration: false,
    priorityScore: 93,
    tags: ["India", "CDSCO", "regulatory", "drug-approval", "NSQ", "spurious-drug", "drug-alert", "india-drug-safety"],
    clinicalUseCases: ["drug safety check", "banned medicine lookup", "NSQ alert", "regulatory status"],
    dataTypes: ["safety-alert", "regulatory-notice"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  {
    id: "pvpi-alerts",
    displayName: "PvPI Drug Safety Alerts",
    category: "India Drug Safety",
    subcategory: "Pharmacovigilance",
    description: "India PvPI (IPC) — pharmacovigilance programme adverse drug reaction alerts and safety communications",
    officialUrl: "https://www.ipc.gov.in/mandates/pvpi",
    countryOrRegion: "India",
    indiaPriority: 2,
    globalPriority: 2,
    sourceAuthorityLevel: "pharmacovigilance",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official IPC/PvPI safety communications. Full text ingestion permitted.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "html",
    updateFrequency: "monthly",
    supportsApi: false,
    supportsBulkDownload: false,
    requiresRegistration: false,
    priorityScore: 93,
    tags: ["India", "IPC", "PvPI", "pharmacovigilance", "adverse-drug-reaction", "drug-safety", "india-drug-safety"],
    clinicalUseCases: ["ADR surveillance", "drug safety warnings", "pharmacovigilance alerts"],
    dataTypes: ["safety-alert", "adr-report"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-18",
  },
  // ── Existing India sources ────────────────────────────────────────────────
  { id: "india-gov", displayName: "India MoHFW / ICMR / NTEP (General)", category: "India Guidelines", subcategory: "Multi-programme", description: "India MoHFW STG, NTEP TB, NCVBDC, NACO, ICMR combined index", officialUrl: "https://mohfw.gov.in", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "national-programme", accessType: "open", licenseStatus: "Government of India — open access", allowedUseNotes: "Official MoHFW documents.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "pdf", updateFrequency: "irregular", supportsApi: false, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 96, tags: ["India", "MoHFW", "ICMR", "STG", "india-guideline"], clinicalUseCases: ["standard treatment guidelines", "disease management"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "icmr-guidelines", displayName: "ICMR Clinical Guidelines", category: "India Guidelines", subcategory: "Research Council", description: "Indian Council of Medical Research clinical guidelines", officialUrl: "https://main.icmr.gov.in", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "Government of India — open access", allowedUseNotes: "ICMR official publications.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "irregular", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 95, tags: ["India", "ICMR", "clinical-guideline", "india-guideline"], clinicalUseCases: ["evidence-based clinical guidance"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "aiims-protocols", displayName: "AIIMS Clinical Protocols", category: "India Guidelines", subcategory: "Tertiary Hospital", description: "All India Institute of Medical Sciences clinical protocols", officialUrl: "https://www.aiims.edu", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "Government of India — open access", allowedUseNotes: "AIIMS official protocols.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "irregular", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 94, tags: ["India", "AIIMS", "clinical-protocol", "india-guideline"], clinicalUseCases: ["tertiary care protocols"], dataTypes: ["clinical-protocol"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  // ── WHO global (priority tier 3) ──────────────────────────────────────────
  { id: "who-guidelines", displayName: "WHO Clinical Guidelines", category: "Global Guidelines", subcategory: "WHO", description: "World Health Organization clinical practice guidelines", officialUrl: "https://www.who.int/publications", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "CC BY-NC-SA 3.0 IGO", allowedUseNotes: "Non-commercial use. Attribution required.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "irregular", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 85, tags: ["WHO", "global-guideline"], clinicalUseCases: ["global clinical guidance"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "who-essential-meds", displayName: "WHO Essential Medicines", category: "Global Guidelines", subcategory: "WHO", description: "WHO Model List of Essential Medicines", officialUrl: "https://www.who.int/groups/expert-committee-on-selection-and-use-of-essential-medicines/essential-medicines-lists", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 1, sourceAuthorityLevel: "formulary", accessType: "open", licenseStatus: "CC BY-NC-SA 3.0 IGO", allowedUseNotes: "Non-commercial use.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "biennial", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 84, tags: ["WHO", "essential-medicines", "formulary"], clinicalUseCases: ["essential medicines", "rational use"], dataTypes: ["drug-list", "formulary"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "who-drug-safety", displayName: "WHO Drug Safety", category: "Global Guidelines", subcategory: "WHO", description: "WHO drug safety communications and pharmacovigilance", officialUrl: "https://www.who.int/teams/regulation-prequalification/pharmacovigilance", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 1, sourceAuthorityLevel: "pharmacovigilance", accessType: "open", licenseStatus: "CC BY-NC-SA 3.0 IGO", allowedUseNotes: "Non-commercial use.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "monthly", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 83, tags: ["WHO", "drug-safety", "pharmacovigilance"], clinicalUseCases: ["global drug safety", "pharmacovigilance"], dataTypes: ["safety-alert"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  // ── International evidence/guidelines (priority tier 4) ───────────────────
  { id: "nice-guidelines", displayName: "NICE Clinical Guidelines", category: "Clinical Guidelines", subcategory: "UK", description: "NICE UK evidence-based clinical recommendations", officialUrl: "https://www.nice.org.uk/guidance", countryOrRegion: "UK", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "© NICE, non-commercial", allowedUseNotes: "Non-commercial clinical reference. No full-text redistribution.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 75, tags: ["NICE", "UK", "clinical-guideline", "evidence-based"], clinicalUseCases: ["UK evidence-based guidance"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "cochrane-summaries", displayName: "Cochrane Systematic Reviews", category: "Clinical Guidelines", subcategory: "Evidence Reviews", description: "Cochrane systematic review summaries", officialUrl: "https://www.cochranelibrary.com", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "evidence-review", accessType: "open", licenseStatus: "CC BY", allowedUseNotes: "Open access summaries.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 74, tags: ["Cochrane", "systematic-review", "evidence-based"], clinicalUseCases: ["evidence synthesis"], dataTypes: ["systematic-review"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "ahrq-reviews", displayName: "AHRQ Evidence Reviews", category: "Clinical Guidelines", subcategory: "US", description: "Agency for Healthcare Research and Quality evidence reviews", officialUrl: "https://www.ahrq.gov/research/findings/evidence-based-reports", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "evidence-review", accessType: "open", licenseStatus: "US Government — public domain", allowedUseNotes: "Public domain.", attributionRequired: false, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 72, tags: ["AHRQ", "US", "evidence-review"], clinicalUseCases: ["evidence-based reviews"], dataTypes: ["evidence-review"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "uspstf", displayName: "USPSTF Recommendations", category: "Clinical Guidelines", subcategory: "US", description: "US Preventive Services Task Force recommendations", officialUrl: "https://www.uspreventiveservicestaskforce.org", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "US Government — public domain", allowedUseNotes: "Public domain.", attributionRequired: false, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 70, tags: ["USPSTF", "US", "preventive-care"], clinicalUseCases: ["preventive services", "screening"], dataTypes: ["recommendation"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  // ── Drug references (priority tier 5) ─────────────────────────────────────
  { id: "dailymed", displayName: "DailyMed Drug Labels", category: "Drug Reference", subcategory: "US FDA", description: "US FDA official drug label database (NLM DailyMed)", officialUrl: "https://dailymed.nlm.nih.gov", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 3, sourceAuthorityLevel: "drug-reference", accessType: "open", licenseStatus: "US Government — public domain", allowedUseNotes: "Public domain.", attributionRequired: false, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "api", updateFrequency: "continuous", supportsApi: true, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 65, tags: ["DailyMed", "drug-label", "FDA", "US"], clinicalUseCases: ["drug label", "prescribing information"], dataTypes: ["drug-monograph"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "openfda-faers", displayName: "OpenFDA FAERS", category: "Drug Reference", subcategory: "US FDA", description: "FDA Adverse Event Reporting System", officialUrl: "https://open.fda.gov/apis/drug/event/", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 3, sourceAuthorityLevel: "pharmacovigilance", accessType: "open", licenseStatus: "CC0", allowedUseNotes: "Public domain.", attributionRequired: false, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "api", updateFrequency: "quarterly", supportsApi: true, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 63, tags: ["OpenFDA", "FAERS", "adverse-event", "pharmacovigilance"], clinicalUseCases: ["adverse drug event reporting", "pharmacovigilance"], dataTypes: ["adr-report"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "pubchem-compounds", displayName: "PubChem Compounds", category: "Drug Reference", subcategory: "Chemistry", description: "NCBI PubChem chemical and pharmacology database", officialUrl: "https://pubchem.ncbi.nlm.nih.gov", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 3, sourceAuthorityLevel: "drug-reference", accessType: "open", licenseStatus: "CC0", allowedUseNotes: "Public domain.", attributionRequired: false, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "api", updateFrequency: "continuous", supportsApi: true, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 60, tags: ["PubChem", "chemistry", "pharmacology"], clinicalUseCases: ["drug chemistry", "pharmacology"], dataTypes: ["chemical-data"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "merck-manual", displayName: "Merck Manual (Professional)", category: "Drug Reference", subcategory: "Clinical Reference", description: "Merck Manual Professional Edition clinical reference", officialUrl: "https://www.merckmanuals.com/professional", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 3, sourceAuthorityLevel: "clinical-tool", accessType: "open", licenseStatus: "© Merck, non-commercial clinical reference", allowedUseNotes: "Non-commercial reference only.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 62, tags: ["Merck", "clinical-reference"], clinicalUseCases: ["clinical reference"], dataTypes: ["clinical-reference"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  // ── Clinical tools / research ─────────────────────────────────────────────
  { id: "pubmed-central", displayName: "PubMed Central (Open Access)", category: "Research", subcategory: "NIH", description: "NIH free full-text archive of biomedical journal articles", officialUrl: "https://www.ncbi.nlm.nih.gov/pmc/", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "evidence-review", accessType: "open", licenseStatus: "Per-article open access licenses", allowedUseNotes: "Open access articles only.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "api", updateFrequency: "continuous", supportsApi: true, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 72, tags: ["PubMed", "research", "NIH", "open-access"], clinicalUseCases: ["biomedical research", "evidence base"], dataTypes: ["research-article"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "wiki-em", displayName: "WikiEM — Emergency Medicine", category: "Clinical Reference", subcategory: "Emergency", description: "Free open-access emergency medicine wiki", officialUrl: "https://wikem.org", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 3, sourceAuthorityLevel: "clinical-tool", accessType: "open", licenseStatus: "CC BY-SA", allowedUseNotes: "Open access.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "api", updateFrequency: "continuous", supportsApi: true, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 65, tags: ["WikiEM", "emergency-medicine", "open-access"], clinicalUseCases: ["emergency procedures", "toxicology", "resuscitation"], dataTypes: ["clinical-reference"], sourceReliabilityLevel: "moderate", lastLicenseReviewAt: "2026-05-18" },
  { id: "mdcalc", displayName: "MDCalc Clinical Calculators", category: "Clinical Tools", subcategory: "Calculators", description: "Medical calculators and clinical decision rules", officialUrl: "https://www.mdcalc.com", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 3, sourceAuthorityLevel: "clinical-tool", accessType: "open", licenseStatus: "© MDCalc — non-commercial", allowedUseNotes: "Non-commercial reference.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 63, tags: ["MDCalc", "calculator", "clinical-decision"], clinicalUseCases: ["risk scores", "clinical calculators"], dataTypes: ["clinical-tool"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "orphadata", displayName: "Orphadata — Rare Diseases", category: "Rare Diseases", subcategory: "Orphanet", description: "Orphanet/Orphadata 10,000+ rare disease profiles (CC BY 4.0)", officialUrl: "https://www.orphanet.org", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "CC BY 4.0", allowedUseNotes: "Open access with attribution.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "annual", supportsApi: false, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 70, tags: ["Orphanet", "rare-disease"], clinicalUseCases: ["rare disease diagnosis", "orphan drug"], dataTypes: ["disease-profile"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "omim", displayName: "OMIM — Online Mendelian Inheritance", category: "Rare Diseases", subcategory: "Genetics", description: "OMIM database of genetic disorders", officialUrl: "https://www.omim.org", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "evidence-review", accessType: "open", licenseStatus: "OMIM — non-commercial", allowedUseNotes: "Non-commercial use.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 68, tags: ["OMIM", "genetics", "rare-disease"], clinicalUseCases: ["genetic disorders", "Mendelian diseases"], dataTypes: ["disease-profile", "genetic-data"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "gene-reviews", displayName: "GeneReviews (NCBI)", category: "Rare Diseases", subcategory: "Genetics", description: "NCBI GeneReviews expert-authored gene-disease articles", officialUrl: "https://www.ncbi.nlm.nih.gov/books/NBK1116/", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "evidence-review", accessType: "open", licenseStatus: "NCBI/NIH — open access", allowedUseNotes: "Open access.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 67, tags: ["GeneReviews", "genetics", "rare-disease"], clinicalUseCases: ["genetic counseling", "rare disease management"], dataTypes: ["disease-review"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "cdc-diseases", displayName: "CDC Disease Information", category: "Clinical Reference", subcategory: "US CDC", description: "US CDC disease and condition information", officialUrl: "https://www.cdc.gov/diseases-conditions", countryOrRegion: "USA", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "US Government — public domain", allowedUseNotes: "Public domain.", attributionRequired: false, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 70, tags: ["CDC", "US", "disease-information"], clinicalUseCases: ["disease management", "public health"], dataTypes: ["disease-information"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "clinicaltrials", displayName: "ClinicalTrials.gov", category: "Research", subcategory: "Trials Registry", description: "US NIH ClinicalTrials.gov trial registry", officialUrl: "https://clinicaltrials.gov", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 3, sourceAuthorityLevel: "evidence-review", accessType: "open", licenseStatus: "US Government — public domain", allowedUseNotes: "Public domain.", attributionRequired: false, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "api", updateFrequency: "continuous", supportsApi: true, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 60, tags: ["ClinicalTrials", "trial-registry", "research"], clinicalUseCases: ["trial eligibility", "research context"], dataTypes: ["trial-record"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  // ── India specialty bodies (new) ──────────────────────────────────────────
  { id: "idsp", displayName: "IDSP — India Disease Surveillance", category: "India Disease Surveillance", subcategory: "National Surveillance", description: "India IDSP — weekly outbreak alerts, disease surveillance reports, epidemic intelligence", officialUrl: "https://idsp.nic.in", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "national-programme", accessType: "open", licenseStatus: "Government of India — open access", allowedUseNotes: "Official MoHFW surveillance data.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "weekly", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 96, tags: ["India", "IDSP", "disease-surveillance", "outbreak", "epidemic", "india-guideline"], clinicalUseCases: ["outbreak alert", "disease surveillance", "epidemic intelligence"], dataTypes: ["surveillance-report", "outbreak-alert"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "ncg-india", displayName: "National Cancer Grid India (NCG / Tata Memorial)", category: "India Guidelines", subcategory: "Oncology", description: "India NCG — National Cancer Grid cancer treatment guidelines, protocols, and multidisciplinary management consensus", officialUrl: "https://www.tmc.gov.in/ncg", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "Government of India — open access", allowedUseNotes: "Official NCG/TMC protocols.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "annual", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 95, tags: ["India", "NCG", "cancer", "oncology", "Tata-Memorial", "india-guideline"], clinicalUseCases: ["cancer treatment", "oncology protocols", "multidisciplinary cancer care"], dataTypes: ["treatment-guideline", "clinical-protocol"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "iap-guidelines", displayName: "IAP — Indian Academy of Pediatrics Guidelines", category: "India Guidelines", subcategory: "Pediatrics", description: "India IAP standard treatment guidelines, immunization schedule, and clinical practice recommendations for paediatric care", officialUrl: "https://iapindia.org/iap-standard-treatment-guidelines", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "IAP — open access", allowedUseNotes: "Official IAP clinical guidelines.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "annual", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 96, tags: ["India", "IAP", "pediatrics", "immunization", "child-health", "india-guideline"], clinicalUseCases: ["paediatric treatment", "immunization", "child health", "neonatal care"], dataTypes: ["treatment-guideline", "vaccine-schedule"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "fogsi-guidelines", displayName: "FOGSI — India OB/GYN Guidelines (GCPR)", category: "India Guidelines", subcategory: "Obstetrics & Gynaecology", description: "India FOGSI good clinical practice recommendations — obstetrics and gynaecology guidelines, preeclampsia, postpartum care, menstrual disorders", officialUrl: "https://www.fogsi.org/good-clinical-practice-recommendations", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "FOGSI — open access", allowedUseNotes: "Official FOGSI GCPR publications.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "annual", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 95, tags: ["India", "FOGSI", "obstetrics", "gynaecology", "preeclampsia", "india-guideline"], clinicalUseCases: ["obstetric management", "gynaecologic care", "high-risk pregnancy", "menstrual disorders"], dataTypes: ["treatment-guideline", "clinical-protocol"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "rssdi-guidelines", displayName: "RSSDI — India Diabetes Guidelines", category: "India Guidelines", subcategory: "Endocrinology", description: "India RSSDI clinical practice recommendations for diabetes — insulin management, T2DM, gestational diabetes, diabetic complications", officialUrl: "https://rssdi.in/guidelines", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "RSSDI — open access", allowedUseNotes: "Official RSSDI clinical recommendations.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "biennial", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 95, tags: ["India", "RSSDI", "diabetes", "insulin", "T2DM", "india-guideline"], clinicalUseCases: ["diabetes management", "insulin therapy", "diabetic complications", "gestational diabetes"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "inasl-guidelines", displayName: "INASL — India Liver Disease Guidelines", category: "India Guidelines", subcategory: "Hepatology", description: "India INASL liver disease guidelines — hepatitis B/C management, cirrhosis, NAFLD, acute liver failure protocols", officialUrl: "https://inasl.com/guidelines", countryOrRegion: "India", indiaPriority: 1, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "INASL — open access", allowedUseNotes: "Official INASL consensus statements.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "irregular", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 94, tags: ["India", "INASL", "liver", "hepatitis", "cirrhosis", "NAFLD", "india-guideline"], clinicalUseCases: ["liver disease management", "hepatitis B/C", "cirrhosis", "NAFLD"], dataTypes: ["treatment-guideline", "consensus-statement"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  // ── Free international clinical references (new) ──────────────────────────
  { id: "litfl", displayName: "LITFL — Life in the Fast Lane", category: "Clinical Reference", subcategory: "Emergency/Critical Care", description: "LITFL free open-access clinical reference — critical care compendium, toxicology library, ECG library, emergency decision tools", officialUrl: "https://litfl.com", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "clinical-tool", accessType: "open", licenseStatus: "CC BY-NC-SA", allowedUseNotes: "Free non-commercial open access.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 73, tags: ["LITFL", "emergency", "critical-care", "toxicology", "ECG", "open-access"], clinicalUseCases: ["emergency medicine", "critical care", "toxidrome identification", "ECG interpretation"], dataTypes: ["clinical-reference"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "radiopaedia", displayName: "Radiopaedia — Radiology Reference", category: "Clinical Reference", subcategory: "Radiology", description: "Radiopaedia free open-access radiology reference — imaging findings, diagnostic criteria, differential diagnosis by modality", officialUrl: "https://radiopaedia.org", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "clinical-tool", accessType: "open", licenseStatus: "CC BY-NC-SA", allowedUseNotes: "Free non-commercial open access.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 72, tags: ["Radiopaedia", "radiology", "imaging", "CT", "MRI", "open-access"], clinicalUseCases: ["imaging interpretation", "radiology differential", "imaging findings"], dataTypes: ["clinical-reference"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "dermnet", displayName: "DermNet NZ — Dermatology Reference", category: "Clinical Reference", subcategory: "Dermatology", description: "DermNet NZ free comprehensive dermatology reference — skin conditions, drug reactions, tropical diseases, clinical features and management", officialUrl: "https://dermnetnz.org", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "clinical-tool", accessType: "open", licenseStatus: "CC BY-NC-ND", allowedUseNotes: "Free non-commercial reference.", attributionRequired: true, redistributionAllowed: false, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 71, tags: ["DermNet", "dermatology", "skin", "rash", "open-access"], clinicalUseCases: ["skin condition diagnosis", "rash differential", "drug reaction identification"], dataTypes: ["clinical-reference"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "surviving-sepsis", displayName: "Surviving Sepsis Campaign Guidelines", category: "Global Guidelines", subcategory: "Critical Care", description: "Surviving Sepsis Campaign — international sepsis and septic shock management guidelines, 1-hour bundle, resuscitation protocols", officialUrl: "https://www.survivingsepsis.org/Guidelines", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "Open access — SCCM/ESICM", allowedUseNotes: "Freely downloadable guideline PDF.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "biennial", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 84, tags: ["Surviving-Sepsis", "sepsis", "critical-care", "ICU", "resuscitation"], clinicalUseCases: ["sepsis management", "septic shock", "ICU resuscitation", "sepsis bundle"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "kdigo-guidelines", displayName: "KDIGO — Kidney Disease Guidelines", category: "Global Guidelines", subcategory: "Nephrology", description: "KDIGO free nephrology guidelines — AKI staging, CKD management, blood pressure in renal disease, glomerulonephritis, transplant", officialUrl: "https://kdigo.org/guidelines/", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "KDIGO — open access (free download)", allowedUseNotes: "Freely downloadable guideline PDFs.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "irregular", supportsApi: false, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 83, tags: ["KDIGO", "nephrology", "AKI", "CKD", "kidney", "transplant"], clinicalUseCases: ["AKI management", "CKD staging", "renal hypertension", "glomerulonephritis"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "gold-copd", displayName: "GOLD — COPD Guidelines", category: "Global Guidelines", subcategory: "Pulmonology", description: "GOLD COPD annual report — COPD diagnosis, GOLD staging (1–4), pharmacological and non-pharmacological management", officialUrl: "https://goldcopd.org/gold-reports/", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "GOLD — open access (free PDF)", allowedUseNotes: "Freely downloadable annual report.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "annual", supportsApi: false, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 82, tags: ["GOLD", "COPD", "pulmonology", "spirometry", "bronchodilator"], clinicalUseCases: ["COPD diagnosis", "COPD staging", "COPD pharmacotherapy", "inhaler selection"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "gina-asthma", displayName: "GINA — Global Asthma Guidelines", category: "Global Guidelines", subcategory: "Pulmonology", description: "GINA annual asthma report — asthma diagnosis, severity classification, step-up/step-down therapy, severe asthma management", officialUrl: "https://ginasthma.org/gina-reports/", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 1, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "GINA — open access (free PDF)", allowedUseNotes: "Freely downloadable annual report.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "annual", supportsApi: false, supportsBulkDownload: true, requiresRegistration: false, priorityScore: 82, tags: ["GINA", "asthma", "pulmonology", "inhaler", "ICS", "step-therapy"], clinicalUseCases: ["asthma diagnosis", "asthma severity", "inhaler step therapy", "severe asthma"], dataTypes: ["treatment-guideline"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "statpearls", displayName: "StatPearls (NCBI) — Free Clinical Textbook", category: "Clinical Reference", subcategory: "Clinical Textbook", description: "StatPearls free NCBI peer-reviewed clinical chapters — diagnosis, workup, treatment and management across all specialties", officialUrl: "https://www.ncbi.nlm.nih.gov/books/NBK430685/", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "evidence-review", accessType: "open", licenseStatus: "NCBI/NIH — open access", allowedUseNotes: "Freely accessible clinical textbook.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 74, tags: ["StatPearls", "NCBI", "clinical-textbook", "open-access", "NIH"], clinicalUseCases: ["clinical diagnosis", "treatment protocols", "medical education"], dataTypes: ["clinical-reference", "evidence-review"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  { id: "wses-guidelines", displayName: "WSES — Emergency Surgery Guidelines", category: "Global Guidelines", subcategory: "Emergency Surgery", description: "WSES fully open-access emergency surgery guidelines — acute abdomen, trauma, septic shock, bowel obstruction, abdominal infections", officialUrl: "https://wjes.biomedcentral.com", countryOrRegion: "Global", indiaPriority: 0, globalPriority: 2, sourceAuthorityLevel: "guideline", accessType: "open", licenseStatus: "CC BY — open access", allowedUseNotes: "Fully open access.", attributionRequired: true, redistributionAllowed: true, localStorageAllowed: true, ingestionMode: "html", updateFrequency: "continuous", supportsApi: false, supportsBulkDownload: false, requiresRegistration: false, priorityScore: 71, tags: ["WSES", "emergency-surgery", "acute-abdomen", "trauma", "open-access"], clinicalUseCases: ["emergency surgery", "acute abdomen", "trauma surgery", "abdominal infections"], dataTypes: ["treatment-guideline", "consensus-statement"], sourceReliabilityLevel: "high", lastLicenseReviewAt: "2026-05-18" },
  {
    id: "nmc-cbme",
    displayName: "NMC — National Medical Commission Competency Based Medical Education",
    category: "India Guidelines",
    subcategory: "Academic Curriculum",
    description: "National Medical Commission (NMC) Competency Based Undergraduate & Postgraduate Medical Education (CBME) curriculum standards and learning objectives",
    officialUrl: "https://www.nmc.org.in",
    countryOrRegion: "India",
    indiaPriority: 1,
    globalPriority: 1,
    sourceAuthorityLevel: "national-programme",
    accessType: "open",
    licenseStatus: "NMC — open access",
    allowedUseNotes: "Official NMC competency standards.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "html",
    updateFrequency: "irregular",
    supportsApi: false,
    supportsBulkDownload: false,
    requiresRegistration: false,
    priorityScore: 97,
    tags: ["India", "NMC", "CBME", "MBBS", "curriculum", "education", "standards", "india-guideline"],
    clinicalUseCases: ["medical curriculum alignment", "clinical competency assessment", "specialty swarm routing"],
    dataTypes: ["academic-standards", "curriculum-objective"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-30"
  },
  {
    id: "pmjay-packages",
    displayName: "PM-JAY — National Health Authority Benefit Packages",
    category: "India Guidelines",
    subcategory: "Health Insurance & Policy",
    description: "Pradhan Mantri Jan Arogya Yojana (PM-JAY) health benefit packages, pre-authorization clinical criteria, and guidelines",
    officialUrl: "https://pmjay.gov.in",
    countryOrRegion: "India",
    indiaPriority: 1,
    globalPriority: 1,
    sourceAuthorityLevel: "national-programme",
    accessType: "open",
    licenseStatus: "NHA — open access",
    allowedUseNotes: "Official PM-JAY package criteria.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "html",
    updateFrequency: "annual",
    supportsApi: false,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 97,
    tags: ["India", "PM-JAY", "NHA", "insurance", "pre-authorization", "clinical-criteria", "india-guideline"],
    clinicalUseCases: ["triage coordinator guidance", "insurance pre-authorization", "procedure eligibility check"],
    dataTypes: ["health-policy", "clinical-criteria"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-30"
  },
  {
    id: "api-india",
    displayName: "API — Association of Physicians of India Guidelines",
    category: "India Guidelines",
    subcategory: "Internal Medicine",
    description: "Association of Physicians of India (API) clinical practice guidelines for adult medical conditions, hypertension, diabetes, and tropical infectious diseases",
    officialUrl: "https://www.apiindia.org",
    countryOrRegion: "India",
    indiaPriority: 2,
    globalPriority: 1,
    sourceAuthorityLevel: "guideline",
    accessType: "open",
    licenseStatus: "API — open access",
    allowedUseNotes: "Official API consensus and treatment guidelines.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "html",
    updateFrequency: "biennial",
    supportsApi: false,
    supportsBulkDownload: false,
    requiresRegistration: false,
    priorityScore: 94,
    tags: ["India", "API", "internal-medicine", "cardiology", "hypertension", "india-guideline"],
    clinicalUseCases: ["adult diagnosis and treatment", "tropical disease management", "cardiovascular guidance"],
    dataTypes: ["treatment-guideline", "consensus-statement"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-30"
  },
  {
    id: "ip-monographs",
    displayName: "IP — Indian Pharmacopoeia monographs",
    category: "India Guidelines",
    subcategory: "Pharmacopoeia Standards",
    description: "Indian Pharmacopoeia Commission (IPC) official active pharmaceutical ingredient monographs, purity standards, and chemical drug testing specifications",
    officialUrl: "https://ipc.gov.in",
    countryOrRegion: "India",
    indiaPriority: 2,
    globalPriority: 2,
    sourceAuthorityLevel: "regulatory",
    accessType: "open",
    licenseStatus: "Government of India — open access",
    allowedUseNotes: "Official Indian Pharmacopoeia specifications.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "html",
    updateFrequency: "annual",
    supportsApi: false,
    supportsBulkDownload: false,
    requiresRegistration: false,
    priorityScore: 93,
    tags: ["India", "IPC", "Pharmacopoeia", "monograph", "drug-standard", "purity", "india-guideline"],
    clinicalUseCases: ["drug purity standard checking", "rational active ingredient identification", "clinical pharmacist validation"],
    dataTypes: ["drug-standard", "regulatory-monograph"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-30"
  },
  {
    id: "who-icd11",
    displayName: "WHO ICD-11 Diagnostic Classifications",
    category: "Global Guidelines",
    subcategory: "Diagnostic Coding & Classifications",
    description: "World Health Organization (WHO) International Classification of Diseases 11th Revision (ICD-11) diagnostic codes and classification hierarchy",
    officialUrl: "https://icd.who.int",
    countryOrRegion: "Global",
    indiaPriority: 0,
    globalPriority: 1,
    sourceAuthorityLevel: "guideline",
    accessType: "open",
    licenseStatus: "WHO — open access API & search",
    allowedUseNotes: "WHO ICD-11 official diagnostic index codes.",
    attributionRequired: true,
    redistributionAllowed: true,
    localStorageAllowed: true,
    ingestionMode: "html",
    updateFrequency: "annual",
    supportsApi: true,
    supportsBulkDownload: true,
    requiresRegistration: false,
    priorityScore: 92,
    tags: ["WHO", "ICD-11", "classification", "diagnostic-code", "pathological-agent", "global-standard"],
    clinicalUseCases: ["clinical diagnosis coding", "consensus report formatting", "pathological classification"],
    dataTypes: ["diagnostic-classification", "clinical-coding"],
    sourceReliabilityLevel: "high",
    lastLicenseReviewAt: "2026-05-30"
  }
];

// Priority multipliers for India-first ranking in query pipeline
export const INDIA_PRIORITY_MULTIPLIERS: Record<string, number> = Object.fromEntries(
  RESOURCE_REGISTRY.map((r) => {
    let mult = 1.0;
    if (r.indiaPriority === 1) mult = 1.35;       // Indian national programme
    else if (r.indiaPriority === 2) mult = 1.25;   // Indian drug/regulatory/formulary
    else if (r.globalPriority === 1) mult = 1.10;  // WHO global
    else if (r.globalPriority === 2) mult = 1.05;  // Top international evidence
    return [r.id, mult];
  })
);

// Domain → crawler ID mapping for URL-based priority lookup
export const DOMAIN_TO_CRAWLER: Record<string, string> = {
  "tbcindia.mohfw.gov.in": "ntep-tb",
  "tbcindia.gov.in": "ntep-tb",
  "naco.mohfw.gov.in": "naco-hiv",
  "naco.gov.in": "naco-hiv",
  "ncvbdc.mohfw.gov.in": "ncvbdc-malaria",
  "nvbdcp.gov.in": "ncvbdc-malaria",
  "nhm.gov.in": "uip-immunization",
  "immunizationacademy.mohfw.gov.in": "uip-immunization",
  "cdsco.gov.in": "cdsco-alerts",
  "ipc.gov.in": "pvpi-alerts",
  "clinicalestablishments.mohfw.gov.in": "india-gov",
  "mohfw.gov.in": "india-gov",
  "main.icmr.gov.in": "icmr-guidelines",
  "icmr.gov.in": "icmr-guidelines",
  "aiims.edu": "aiims-protocols",
  "who.int": "who-guidelines",
  "nice.org.uk": "nice-guidelines",
  "cochranelibrary.com": "cochrane-summaries",
  "ahrq.gov": "ahrq-reviews",
  "uspreventiveservicestaskforce.org": "uspstf",
  "dailymed.nlm.nih.gov": "dailymed",
  "open.fda.gov": "openfda-faers",
  "pubchem.ncbi.nlm.nih.gov": "pubchem-compounds",
  "merckmanuals.com": "merck-manual",
  "ncbi.nlm.nih.gov": "pubmed-central",
  "wikem.org": "wiki-em",
  "mdcalc.com": "mdcalc",
  "orpha.net": "orphadata",
  "orphadata.com": "orphadata",
  "omim.org": "omim",
  "cdc.gov": "cdc-diseases",
  "clinicaltrials.gov": "clinicaltrials",
  // India specialty bodies
  "idsp.nic.in": "idsp",
  "tmc.gov.in": "ncg-india",
  "iapindia.org": "iap-guidelines",
  "fogsi.org": "fogsi-guidelines",
  "rssdi.in": "rssdi-guidelines",
  "inasl.com": "inasl-guidelines",
  // Free international clinical references
  "litfl.com": "litfl",
  "radiopaedia.org": "radiopaedia",
  "dermnetnz.org": "dermnet",
  "survivingsepsis.org": "surviving-sepsis",
  "kdigo.org": "kdigo-guidelines",
  "goldcopd.org": "gold-copd",
  "ginasthma.org": "gina-asthma",
  "wjes.biomedcentral.com": "wses-guidelines",
  // 5 New clinical knowledge bases
  "nmc.org.in": "nmc-cbme",
  "pmjay.gov.in": "pmjay-packages",
  "apiindia.org": "api-india",
  "ipmonograph.in": "ip-monographs",
  "icd.who.int": "who-icd11",
};

export function getPriorityMultiplierForUrl(sourceUrl: string | null | undefined): number {
  if (!sourceUrl) return 1.0;
  try {
    const domain = new URL(sourceUrl).hostname.replace(/^www\./, "");
    const crawlerId = DOMAIN_TO_CRAWLER[domain];
    if (!crawlerId) return 1.0;
    return INDIA_PRIORITY_MULTIPLIERS[crawlerId] ?? 1.0;
  } catch {
    return 1.0;
  }
}

export function getResourceMeta(crawlerId: string): ResourceMeta | undefined {
  return RESOURCE_REGISTRY.find((r) => r.id === crawlerId);
}
